<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class MBimbingan extends CI_Model
{

    public $table = 'bimbingan';
    public $id = 'id_bimbingan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_bimbingan', $q);
	$this->db->or_like('id_dosen', $q);
	$this->db->or_like('id_mahasiswa', $q);
	$this->db->or_like('npm', $q);
	$this->db->or_like('tanggal_bimbingan', $q);
	$this->db->or_like('materi', $q);
	$this->db->or_like('upload_file', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        // print_r($_SESSION);die;
    //join tabel dosen dan tabel mahasiswa
    $this->db->select('b.*,d.nama_dosen,m.nama_mahasiswa,m.npm');
    $this->db->from('bimbingan b');
    $this->db->join('dosen d', 'd.id_dosen = b.id_dosen');
    $this->db->join('mahasiswa m', 'm.id_mahasiswa = b.id_mahasiswa');
    $nama_lengkap=$_SESSION['nama_lengkap'];

    if($_SESSION['hak_akses']=='D'){
        $this->db->where('d.nama_dosen',$nama_lengkap);
    }

    if($_SESSION['hak_akses']=='M'){
        $this->db->where('m.nama_mahasiswa',$nama_lengkap);
    }

    $this->db->order_by('b.id_bimbingan', $this->order);
 //    $this->db->like('b.id_bimbingan', $q);
	// $this->db->or_like('b.id_dosen', $q);
	// $this->db->or_like('b.id_mahasiswa', $q);
	// $this->db->or_like('b.npm', $q);
	// $this->db->or_like('b.tanggal_bimbingan', $q);
	// $this->db->or_like('b.materi', $q);
	// $this->db->or_like('b.upload_file', $q);
	$this->db->limit($limit, $start);
    // print_r($this->db->get()->result());die;
    return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file MBimbingan.php */
/* Location: ./application/models/MBimbingan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-07-21 06:56:25 */
/* http://harviacode.com */