<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class MBuku_bimbingan extends CI_Model
{

    public $table = 'buku_bimbingan';
    public $id = 'id_buku_bimbingan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
    $this->db->like('id_buku_bimbingan', $q);
	$this->db->or_like('npm', $q);
	$this->db->or_like('id_mahasiswa', $q);
	$this->db->or_like('deadline', $q);
	$this->db->or_like('tanggal_kumpul', $q);
	$this->db->or_like('upload_file', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
    //join tabel mahasiswa
    $this->db->select('bk.*,m.npm,m.nama_mahasiswa');
    $this->db->from('buku_bimbingan bk');
    $this->db->join('mahasiswa m', 'm.id_mahasiswa = bk.id_mahasiswa');

    $this->db->order_by('bk.id_buku_bimbingan', $this->order);
    $this->db->like('bk.id_buku_bimbingan', $q);
	$this->db->or_like('bk.npm', $q);
	$this->db->or_like('bk.id_mahasiswa', $q);
	$this->db->or_like('bk.deadline', $q);
	$this->db->or_like('bk.tanggal_kumpul', $q);
	$this->db->or_like('bk.upload_file', $q);
	$this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file MBuku_bimbingan.php */
/* Location: ./application/models/MBuku_bimbingan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-07-19 17:18:24 */
/* http://harviacode.com */