<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class MLaporan_kelulusan extends CI_Model
{

    public $table = 'laporan_kelulusan';
    public $id = 'id_laporan_kelulusan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_laporan_kelulusan', $q);
	$this->db->or_like('tanggal_sidang', $q);
	$this->db->or_like('id_mahasiswa', $q);
	$this->db->or_like('id_dosen', $q);
	$this->db->or_like('id_penguji', $q);
	$this->db->or_like('hasil_keputusan_sidang', $q);
	$this->db->or_like('catatan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL, $akhir=NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_laporan_kelulusan', $q);
	$this->db->or_like('tanggal_sidang', $q);
	$this->db->or_like('id_mahasiswa', $q);
	$this->db->or_like('id_dosen', $q);
	$this->db->or_like('id_penguji', $q);
	$this->db->or_like('hasil_keputusan_sidang', $q);
	$this->db->or_like('catatan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    function get_laporan_kelulusan( $awal = NULL , $akhir = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->where('tanggal_sidang >=', $awal);
        $this->db->where('tanggal_sidang <=', $akhir);
       //return $this->db->get($this->table)->result();
       $this->db->get($this->table)->result();
       echo $this->db->last_query(); exit;
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file MLaporan_kelulusan.php */
/* Location: ./application/models/MLaporan_kelulusan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-07-27 12:11:26 */
/* http://harviacode.com */