<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class MMahasiswa extends CI_Model
{

    public $table = 'mahasiswa';
    public $id = 'id_mahasiswa';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

     function get_mhs()
    {
        $username= $_SESSION['username'] ;
        $this->db->join('user','user.npm=mahasiswa.npm');
        $this->db->where('user.username',$username);
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_mahasiswa', $q);
	$this->db->or_like('npm', $q);
	$this->db->or_like('nama_mahasiswa', $q);
	$this->db->or_like('tingkat', $q);
	$this->db->or_like('Jenis_Kelamin', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_mahasiswa', $q);
	$this->db->or_like('npm', $q);
	$this->db->or_like('nama_mahasiswa', $q);
	$this->db->or_like('tingkat', $q);
	$this->db->or_like('Jenis_Kelamin', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file MMahasiswa.php */
/* Location: ./application/models/MMahasiswa.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-08-10 19:06:48 */
/* http://harviacode.com */